import React from "react";

function Terms() {
  return (
    <section className="bg-primary">
      <div className="px-8 md:px-40 py-4 mx-auto">
        <h2 className="font-Boston text-2xl text-center text-white py-10">
          TERMS and CONDITIONS
        </h2>
        <p className="text-sm font-Opensans text-justify text-white leading-6">
          Dogface Army is a collection of digital artworks (NFTs) running on the
          Ethereum network. This website is only an interface allowing
          participants to exchange digital collectibles. Users are entirely
          responsible for the safety and management of their own private
          Ethereum wallets and validating all transactions and contracts
          generated by this website before approval. Furthermore, as the Dogface
          Army smart contract runs on the Ethereum network, there is no ability
          to undo, reverse, or restore any transactions.
        </p>
        <p className="text-sm font-Opensans text-justify text-white leading-6 mt-8">
          This website and its connected services are provided “as is” and “as
          available” without warranty of any kind. By using this website you are
          accepting sole responsibility for any and all transactions involving
          Dogface Army digital collectibles.
        </p>
        <h2 className="font-Boston text-2xl text-center text-white py-10">
          OWNERSHIP
        </h2>
        <ul className="text-white list-decimal leading-6 space-y-5 text-sm">
          <li className="">
            You Own the NFT. Each Dogface Army is an NFT on the Ethereum
            blockchain. When you purchase an NFT, you own the underlying Dogface
            Army, the Art, completely. Ownership of the NFT is mediated entirely
            by the Smart Contract and the Ethereum Network: at no point may we
            seize, freeze, or otherwise modify the ownership of any Dogface
            Army.
          </li>
          <li>
            Personal Use. Subject to your continued compliance with these Terms,
            NFT L4B LTD grants you a worldwide, royalty-free license to use,
            copy, and display the purchased Art, along with any extensions that
            you choose to create or use, solely for the following purposes: (i)
            for your own personal, non-commercial use; (ii) as part of a
            marketplace that permits the purchase and sale of your Dogface Army,
            provided that the marketplace cryptographically verifies each
            Dogface Army owner’s rights to display the Art for their Dogface
            Army to ensure that only the actual owner can display the Art; or
            (iii) as part of a third party website or application that permits
            the inclusion, involvement, or participation of your Dogface Army,
            provided that the website/application cryptographically verifies
            each Dogface Army owner’s rights to display the Art for their
            Dogface Army to ensure that only the actual owner can display the
            Art, and provided that the Art is no longer visible once the owner
            of the Dogface Army leaves the website/application.
          </li>
          <li>
            Commercial Use. Subject to your continued compliance with these
            Terms, NFT L4B LTD grants you an unlimited, worldwide license to
            use, copy, and display the purchased Art for the purpose of creating
            derivative works based upon the Art (“Commercial Use”). Examples of
            such Commercial Use would e.g. be the use of the Art to produce and
            sell merchandise products (T-Shirts etc.) displaying copies of the
            Art. For the sake of clarity, nothing in this Section will be deemed
            to restrict you from
            <ul className="text-white list-disc text-sm leading-6 p-6">
              <li>
                owning or operating a marketplace that permits the use and sale
                of Dogface Army generally, provided that the marketplace
                cryptographically verifies each Dogface Army owner’s rights to
                display the Art for their Dogface Army to ensure that only the
                actual owner can display the Art;
              </li>
              <li>
                owning or operating a third party website or application that
                permits the inclusion, involvement, or participation of Dogface
                Army generally, provided that the third party website or
                application cryptographically verifies each Dogface Army owner’s
                rights to display the Art for their Dogface Army to ensure that
                only the actual owner can display the Art, and provided that the
                Art is no longer visible once the owner of the Purchased Dogface
                Army leaves the website/application; or{" "}
              </li>
              <li>Earning revenue from any of the foregoing.</li>
            </ul>
          </li>
        </ul>
      </div>
    </section>
  );
}

export default Terms;
